version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./install-plugin.sh:/tmp/install-plugin.sh
    entrypoint: >
       bash -c "chmod +x /tmp/install-plugin.sh &&
                /tmp/install-plugin.sh ${PLUGIN} && 
                /tmp/install-plugin.sh repository-s3 && 
               docker-entrypoint.sh"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
       - 5601:5601
    networks:
      - esnet

volumes:
  esdata:
    driver: local

networks:
  esnet: